version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    # 한글 설정
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    hostname: redis

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    volumes:
      - mongodb:/data/db
    command: ["mongod", "--auth"]
    hostname: mongo

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_insight
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    networks:
      - app-network
    hostname: mongo-express

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - REDIS_URL=redis://redis:6379
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GCLOUD_STORAGE_BUCKET=${GCLOUD_STORAGE_BUCKET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOVA_API_KEY=${CLOVA_API_KEY}
      - CLOVA_CLIENT_ID=${CLOVA_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GCP_TYPE=${GCP_TYPE}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_PRIVATE_KEY_ID=${GCP_PRIVATE_KEY_ID}
      - GCP_PRIVATE_KEY=${GCP_PRIVATE_KEY}
      - GCP_CLIENT_EMAIL=${GCP_CLIENT_EMAIL}
      - GCP_CLIENT_ID=${GCP_CLIENT_ID}
      - GCP_AUTH_URI=${GCP_AUTH_URI}
      - GCP_TOKEN_URI=${GCP_TOKEN_URI}
      - GCP_AUTH_PROVIDER_X509_CERT_URL=${GCP_AUTH_PROVIDER_X509_CERT_URL}
      - GCP_CLIENT_X509_CERT_URL=${GCP_CLIENT_X509_CERT_URL}
      - GCP_UNIVERSE_DOMAIN=${GCP_UNIVERSE_DOMAIN}
      - MONGO_DOCKER_URL=${MONGO_DOCKER_URL}
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
      - mongodb
    networks:
      - app-network

  

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  mongodb:
